name: status

on: [ pull_request, push]

jobs:
  run-reports:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: bryanmacfarlane/project-reports-action@v1-alpha4
        with: 
          token: ${{ secrets.PROJECT_TOKEN }}
          configPath: reports.yaml
      - if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com     
          git pull origin master          
          git add ./_reports
          git commit -a -m "adding reports"
          git push origin master
      
